name: Create release
on:
  workflow_dispatch:
    inputs:
      releasename:
        description: 'This is just a test'
        type: text
        required: true
      isbeta:
        description: 'Feels like a beta?'
        required: true
        type: boolean

jobs:
  log-the-inputs:
    #runs-on: [ self-hosted ]
    #runs-on: [ self-hosted ]
    runs-on: [ ubuntu-latest ]
    
    steps:
      - run: |
          echo "ReleaseName: $RELEASENAME"
          echo "Tags: $ISBETA"
        env:
#          LEVEL: ${{ inputs.releasename }}
          TAGS: ${{ inputs.isbeta }}



            
