name: Create Release
on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Enter a release name, will create a tag and a release'
        required: true
        type: string
      # is_unstable_release:
      #   description: 'Consider the release unstable?'
      #   required: false
      #   type: boolean


jobs:
  print-tag:
#    runs-on: [ self-hosted ]     
    runs-on: ubuntu-latest

    steps:
      - name: Woop
        run: |
          echo  The is release is named:  ${{ inputs.release_name }} 
 
